package POJO;
// Generated 17 mars 2016 10:43:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Astuce generated by hbm2java
 */
@Entity
@Table(name="astuce"
    ,catalog="nekoatsume"
)
public class Astuce  implements java.io.Serializable {


     private Integer id;
     private Tablechat tablechat;
     private Utilisateur utilisateur;
     private String description;
     private Integer voteplus;
     private Integer votemoins;
     private String titre;

    public Astuce() {
    }

    public Astuce(Tablechat tablechat, Utilisateur utilisateur, String description, Integer voteplus, Integer votemoins, String titre) {
       this.tablechat = tablechat;
       this.utilisateur = utilisateur;
       this.description = description;
       this.voteplus = voteplus;
       this.votemoins = votemoins;
       this.titre = titre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_chat")
    public Tablechat getTablechat() {
        return this.tablechat;
    }
    
    public void setTablechat(Tablechat tablechat) {
        this.tablechat = tablechat;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_utilisateur")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="voteplus")
    public Integer getVoteplus() {
        return this.voteplus;
    }
    
    public void setVoteplus(Integer voteplus) {
        this.voteplus = voteplus;
    }

    
    @Column(name="votemoins")
    public Integer getVotemoins() {
        return this.votemoins;
    }
    
    public void setVotemoins(Integer votemoins) {
        this.votemoins = votemoins;
    }

    
    @Column(name="titre", length=50)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }




}


