package POJO;
// Generated 17 mars 2016 10:43:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tablechat generated by hbm2java
 */
@Entity
@Table(name="tablechat"
    ,catalog="nekoatsume"
)
public class Tablechat  implements java.io.Serializable {


     private Integer idChat;
     private String nom;
     private String nomJaponais;
     private String description;
     private String personnalite;
     private Integer niveau;
     private Integer rare;
     private Set<Astuce> astuces = new HashSet<Astuce>(0);

    public Tablechat() {
    }

    public Tablechat(String nom, String nomJaponais, String description, String personnalite, Integer niveau, Integer rare, Set<Astuce> astuces) {
       this.nom = nom;
       this.nomJaponais = nomJaponais;
       this.description = description;
       this.personnalite = personnalite;
       this.niveau = niveau;
       this.rare = rare;
       this.astuces = astuces;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_chat", unique=true, nullable=false)
    public Integer getIdChat() {
        return this.idChat;
    }
    
    public void setIdChat(Integer idChat) {
        this.idChat = idChat;
    }

    
    @Column(name="NOM", length=50)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="NOM_JAPONAIS", length=50)
    public String getNomJaponais() {
        return this.nomJaponais;
    }
    
    public void setNomJaponais(String nomJaponais) {
        this.nomJaponais = nomJaponais;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="PERSONNALITE", length=50)
    public String getPersonnalite() {
        return this.personnalite;
    }
    
    public void setPersonnalite(String personnalite) {
        this.personnalite = personnalite;
    }

    
    @Column(name="NIVEAU")
    public Integer getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Integer niveau) {
        this.niveau = niveau;
    }

    
    @Column(name="RARE")
    public Integer getRare() {
        return this.rare;
    }
    
    public void setRare(Integer rare) {
        this.rare = rare;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tablechat")
    public Set<Astuce> getAstuces() {
        return this.astuces;
    }
    
    public void setAstuces(Set<Astuce> astuces) {
        this.astuces = astuces;
    }




}


