package POJO;
// Generated 17 mars 2016 10:43:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,catalog="nekoatsume"
)
public class Utilisateur  implements java.io.Serializable {


     private Integer idUtilisateur;
     private String pseudoUtilisateur;
     private String mdp;
     private String nomUtilisateur;
     private String prenomUtilisateur;
     private String email;
     private Boolean admin;
     private Set<Astuce> astuces = new HashSet<Astuce>(0);

    public Utilisateur() {
    }

    public Utilisateur(String pseudoUtilisateur, String mdp, String nomUtilisateur, String prenomUtilisateur, String email, Boolean admin, Set<Astuce> astuces) {
       this.pseudoUtilisateur = pseudoUtilisateur;
       this.mdp = mdp;
       this.nomUtilisateur = nomUtilisateur;
       this.prenomUtilisateur = prenomUtilisateur;
       this.email = email;
       this.admin = admin;
       this.astuces = astuces;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_utilisateur", unique=true, nullable=false)
    public Integer getIdUtilisateur() {
        return this.idUtilisateur;
    }
    
    public void setIdUtilisateur(Integer idUtilisateur) {
        this.idUtilisateur = idUtilisateur;
    }

    
    @Column(name="pseudo_utilisateur", length=50)
    public String getPseudoUtilisateur() {
        return this.pseudoUtilisateur;
    }
    
    public void setPseudoUtilisateur(String pseudoUtilisateur) {
        this.pseudoUtilisateur = pseudoUtilisateur;
    }

    
    @Column(name="mdp", length=50)
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    
    @Column(name="nom_utilisateur", length=50)
    public String getNomUtilisateur() {
        return this.nomUtilisateur;
    }
    
    public void setNomUtilisateur(String nomUtilisateur) {
        this.nomUtilisateur = nomUtilisateur;
    }

    
    @Column(name="prenom_utilisateur", length=50)
    public String getPrenomUtilisateur() {
        return this.prenomUtilisateur;
    }
    
    public void setPrenomUtilisateur(String prenomUtilisateur) {
        this.prenomUtilisateur = prenomUtilisateur;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="admin")
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set<Astuce> getAstuces() {
        return this.astuces;
    }
    
    public void setAstuces(Set<Astuce> astuces) {
        this.astuces = astuces;
    }




}


